#####
name: Node.js CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Build Docker image
        run: docker build -t my-app-dev:1.0 -f Dockerfile.dev .

      - name: Run Tests
        run: docker run -e CI=true my-app-dev:1.0 npm run test -- --coverage --watchAll=false
